### ISSUE TITLE
Hidden and cell state in attentional sentence decoder

### ISSUE THREAD

**Issue by WANGCHENYU123** [tengfeixue-victor/Medical-Report-Generation#2]
I found the "embed_h" and "embed_c" are the same in "Atten_Sen_Decoder" class in utils/models.py

self.embed_h = nn.Linear(num_global_features + num_conv1d_out * sen_enco_num_layers,
                                 hidden_size * decoder_num_layers)
self.embed_c = nn.Linear(num_global_features + num_conv1d_out * sen_enco_num_layers,
                                 hidden_size * decoder_num_layers)

Could you please explain it? I think they should be different. Thank you very much.

**Comment by tengfeixue-victor** [comment]
Hi,
I had a look. They both take the "con_features" (global feature and sentence vector), so they have the same dimensions.
Feel free to correct me if I am wrong. I wrote these codes a year ago, and I might forget some details.
