### ISSUE TITLE
The use of local features

### ISSUE THREAD

**Issue by WANGCHENYU123** [tengfeixue-victor/Medical-Report-Generation#3]
In the paper, the authors described that sentence generative model used the global features as inputs and attentional sentence decoder used the regional features and previously generated sentences as a multimodal inputs, but I found that you used global features in the attentional sentence decoder, but not regional features (you combined global features and sentence topic vectors generated from the sentence encoder)

In train.py 56: "finding_decoder = Atten_Sen_Decoder(....)"
In train.py 100: " fin_targets, predicted_fin = finding_decoder(global_feas, global_topic_vec, findings, fin_lengths)"

In class Atten_Sen_Decoder in utils/models.py 163: "def forward(self, global_features, topic_vector, findings, fin_lengths):"
In utils/models.py 166: " last_input, last_state = self._combine_vis_text(global_features, topic_vector)"
In utils/models.py 239: "def _combine_vis_text(self, global_features, sen_vec):"

Could you please explain my questions about the use of regional features?

In addition, I have re-produced your codes for several times, and I found the scores of metrics were not as good as you show. 

What's more, I noticed that the scores of metrics you show are much lower than original work, could you explain what differences between your re-implemented work and the original work are?

Merry Christmas. Thank you very much.

**Comment by tengfeixue-victor** [comment]
Hi,
Sorry for the late reply. The results of re-implementation for Conv1d model works similarly as the paper, but the attention model has issues, I also could not get that good results as shown in the paper. 
Feel free to change codes based on your understanding! I no longer work on this field, sorry if I could not answer all your questions.

**Comment by WANGCHENYU123** [comment]
Hi,
Thanks for your clear reply. 
I am really interested to your re-implementation. Could you please tell me the reason why you re-implement this work? And do you have a document corresponding with your code, such as a report, thesis or published paper? If you have, I am really honour to read it. 
Thank you very much.

**Comment by tengfeixue-victor** [comment]
Hi,
Thanks for your interest! I re-implemented it in a 2020 summer internship (Sydney). I no longer work on this medical report generation field after that, so I do not have those publications that you expect to follow in this field.
I think you can take this code as a baseline and try to improve it. The conv1d model should work well, but the attention one is not good as the original paper.
Good luck!

**Comment by WANGCHENYU123** [comment]
Hi,

Thanks for your reply. 

Could I further confirm if your public code only use conv1d model without attention mechanism? In other words, my understanding is that you did not public the code with attention mechanism, is it right?
 
Thank you very much.

**Comment by tengfeixue-victor** [comment]
yes! you are correct
